include("shared.lua")
include("cl_extensions.lua")
include("sh_hooks.lua")
include("sh_meta.lua")
include("cl_hooks.lua")
include("cl_menu.lua")
include("cl_networking.lua")
include("cl_voice.lua")
include("vgui_slidingtext.lua")
include("vgui_ttotext.lua")
include("vgui_weaponselection.lua")
include("sh_config.lua")
include("sh_admin.lua")
include("sh_language.lua")
include("sh_lastrequest.lua")
include("games/freeday.lua")
include("games/kf.lua")
include("games/race.lua")
include("games/shot4shot.lua")
include("games/warday.lua")
include("games/zombie.lua")
include("games/scoutzknivez.lua")
include("languages/english.lua")

surface.CreateFont("qel", {font = "Roboto", size = 64, weight = 1000, antialias = true})
surface.CreateFont("qxl", {font = "Roboto", size = 48, weight = 1000, antialias = true})
surface.CreateFont("qlg", {font = "Roboto", size = 32, weight = 1000, antialias = true})
surface.CreateFont("qmd", {font = "Roboto", size = 24, weight = 1000, antialias = true})
surface.CreateFont("qsm", {font = "Roboto", size = 20, weight = 1000, antialias = true})
surface.CreateFont("qlt", {font = "Roboto", size = 16, weight = 750, antialias = true})
surface.CreateFont("qtn", {font = "Roboto", size = 12, weight = 750, antialias = true})
