include("shared.lua")
include("sh_hooks.lua")
include("sh_meta.lua")
include("cl_extensions.lua")
include("cl_hooks.lua")
include("cl_menu.lua")
include("cl_networking.lua")
include("cl_voice.lua")
include("sh_config.lua")
include("sh_admin.lua")
include("sh_language.lua")
include("languages/english.lua")

surface.CreateFont("qlg", {font = "Arial", size = 32, weight = 1000, antialias = true})
surface.CreateFont("qmd", {font = "Arial", size = 24, weight = 1000, antialias = true})
surface.CreateFont("qsm", {font = "Arial", size = 20, weight = 1000, antialias = true})
surface.CreateFont("qlt", {font = "Arial", size = 16, weight = 750, antialias = true})
surface.CreateFont("qtn", {font = "Arial", size = 12, weight = 750, antialias = true})
