CreateConVar("jb_round_limit", "30", FCVAR_NOTIFY, "Max round limit before trying to change map.")
CreateConVar("jb_time_limit", "900", FCVAR_NOTIFY, "Round time limit in seconds.")
CreateConVar("jb_ratio", "4", FCVAR_NOTIFY, "Inmate to Guard ratio.")

GM.Ratio = GetConVar("jb_ratio"):GetInt()

util.AddNetworkString("GameData")
util.AddNetworkString("LastRequest")
util.AddNetworkString("PlayerDeath")
util.AddNetworkString("WardenPings")
util.AddNetworkString("SendLastRequests")
util.AddNetworkString("SendKeys")
util.AddNetworkString("UpdateMapVote")
util.AddNetworkString("MapWinner")
util.AddNetworkString("DrawMapVote")
util.AddNetworkString("VoteMap")

resource.AddWorkshop("1103045167")
resource.AddWorkshop("1097131782")

AddCSLuaFile("cl_init.lua")
AddCSLuaFile("shared.lua")
AddCSLuaFile("sh_meta.lua")
AddCSLuaFile("sh_hooks.lua")
AddCSLuaFile("cl_extensions.lua")
AddCSLuaFile("cl_menu.lua")
AddCSLuaFile("cl_networking.lua")
AddCSLuaFile("cl_voice.lua")
AddCSLuaFile("cl_hooks.lua")
AddCSLuaFile("sh_config.lua")
AddCSLuaFile("sh_admin.lua")
AddCSLuaFile("sh_language.lua")
AddCSLuaFile("languages/english.lua")
include("shared.lua")
include("sv_commands.lua")
include("sv_rounds.lua")
include("sv_hooks.lua")
include("sv_meta.lua")
include("sv_warden.lua")
include("sv_hooks.lua")
include("sh_meta.lua")
include("sh_hooks.lua")
include("sh_config.lua")
include("sh_admin.lua")
include("sh_language.lua")
include("sv_lastrequest.lua")
include("sv_networking.lua")
include("games/freeday.lua")
include("games/kf.lua")
include("games/race.lua")
include("games/shot4shot.lua")
include("games/warday.lua")
include("languages/english.lua")
