CreateConVar("jb_round_limit", "30", FCVAR_NOTIFY, "Max round limit before trying to change map.")
CreateConVar("jb_time_limit", "900", FCVAR_NOTIFY, "Round time limit in seconds.")
CreateConVar("jb_ratio", "4", FCVAR_NOTIFY, "Inmate to Guard ratio.")

GM.Ratio = GetConVar("jb_ratio"):GetInt()

util.AddNetworkString("JB_GameData")
util.AddNetworkString("JB_LastRequest")
util.AddNetworkString("JB_LastRequests")
util.AddNetworkString("JB_Marker")
util.AddNetworkString("JB_SendKeys")
util.AddNetworkString("JB_UpdateMapVote")
util.AddNetworkString("JB_MapWinner")
util.AddNetworkString("JB_DrawMapVote")
util.AddNetworkString("JB_VoteMap")
util.AddNetworkString("JB_AddNotice")
util.AddNetworkString("JB_LR")
util.AddNetworkString("JB_SpawnProp")

resource.AddWorkshop("1103045167")
resource.AddWorkshop("1097131782")

AddCSLuaFile("cl_init.lua")
AddCSLuaFile("shared.lua")
AddCSLuaFile("sh_meta.lua")
AddCSLuaFile("sh_hooks.lua")
AddCSLuaFile("cl_extensions.lua")
AddCSLuaFile("cl_menu.lua")
AddCSLuaFile("cl_networking.lua")
AddCSLuaFile("cl_voice.lua")
AddCSLuaFile("cl_hooks.lua")
AddCSLuaFile("vgui_slidingtext.lua")
AddCSLuaFile("vgui_ttotext.lua")
AddCSLuaFile("vgui_weaponselection.lua")
AddCSLuaFile("sh_config.lua")
AddCSLuaFile("sh_admin.lua")
AddCSLuaFile("sh_language.lua")
AddCSLuaFile("sh_lastrequest.lua")
AddCSLuaFile("languages/english.lua")
AddCSLuaFile("games/freeday.lua")
AddCSLuaFile("games/kf.lua")
AddCSLuaFile("games/race.lua")
AddCSLuaFile("games/shot4shot.lua")
AddCSLuaFile("games/warday.lua")
AddCSLuaFile("games/zombie.lua")
AddCSLuaFile("games/scoutzknivez.lua")


include("shared.lua")
include("sv_commands.lua")
include("sv_rounds.lua")
include("sv_hooks.lua")
include("sv_meta.lua")
include("sv_warden.lua")
include("sv_hooks.lua")
include("sh_meta.lua")
include("sh_hooks.lua")
include("sh_config.lua")
include("sh_admin.lua")
include("sh_language.lua")
include("sh_lastrequest.lua")
include("sv_networking.lua")
include("games/freeday.lua")
include("games/kf.lua")
include("games/race.lua")
include("games/shot4shot.lua")
include("games/warday.lua")
include("games/zombie.lua")
include("games/scoutzknivez.lua")
include("languages/english.lua")
